[@@@ocaml.text
  " This module gives access to the same version/build information returned by\n\
  \    [Command]-based executables when called with the [-version] or [-build-info] flags\n\
  \    by [$0 version (-build-info | -version)] or [$0 (-build-info | -version)].\n\n\
  \    Here's how it works: we arrange for the build system to, at link time, include an\n\
  \    object file that defines symbols that version_util.ml uses to get the strings that\n\
  \    contain the information that this module provides.  When building with OMake, our\n\
  \    OMakeroot runs build_info.sh to generate *.build_info.c with the symbols and that \
   is\n\
  \    linked in.\n"]

open! Core

val version_list : string list [@@ocaml.doc " All hg repos and their revision. "]

val version : string
[@@ocaml.doc
  " Like [version_list] but space separated. Consider using [version_list] instead. "]

module Version : sig
  type t =
    { repo : string
    ; version : string
    }
  [@@ocaml.doc
    " [t] is the structured representation of a single entry from [version_list]. "]
  [@@deriving sexp_of]

  include sig
    [@@@ocaml.warning "-32"]

    val sexp_of_t : t -> Sexplib0.Sexp.t
  end
  [@@ocaml.doc "@inline"] [@@merlin.hide]

  val parse1 : string -> t Or_error.t
  [@@ocaml.doc
    " Parse a single line of version-util. It's almost always better to use one of the\n\
    \      functions below, because applying this to [Version_util.version] results in the\n\
    \      following weird behaviors:\n\n\
    \      - NO_VERSION_UTIL gets parsed { repo = \"NO_VERSION\"; version=\"UTIL\" }\n\
    \      - \"repo1_rev1 repo2_rev2\" gets parsed as { repo = \"repo1_rev1 repo2\"; \
     version = \"rev2\" }\n\
    \  "]

  [@@@ocaml.text
    " In the following functions [Error _] means the format is unparsable, [Ok None] means\n\
    \      the version is NO_VERSION_UTIL. "]

  val parse_list : string list -> t list option Or_error.t
  val parse_lines : string -> t list option Or_error.t
  val current_version : unit -> t list option

  [@@@ocaml.text
    " The [_present] functions return [Error] instead of [None] when there's no version\n\
    \      util. There is no version util during most builds. "]

  val parse_list_present : string list -> t list Or_error.t
  val parse_lines_present : string -> t list Or_error.t
  val current_version_present : unit -> t list Or_error.t
end

val arg_spec : (string * Arg.spec * string) list

module Application_specific_fields : sig
  type t = Sexp.t String.Map.t [@@deriving sexp]

  include sig
    [@@@ocaml.warning "-32"]

    include Sexplib0.Sexpable.S with type t := t
  end
  [@@ocaml.doc "@inline"] [@@merlin.hide]
end
[@@ocaml.doc
  " [Application_specific_fields] is a single field in the build-info sexp that holds\n\
  \    a [Sexp.t String.Map.t], which can be chosen by the application to hold custom\n\
  \    fields that it needs. "]

val build_info : string
[@@ocaml.doc
  " Various additional information about the circumstances of the build: who built it,\n\
  \    when, on what machine, etc.\n\
  \    [build_info] is the information as it was generated by the build system.\n\
  \    [reprint_build_info] parses and prints the string back, which alters a bit the \
   layout\n\
  \    and order of the fields but more importantly allows to display times in the current\n\
  \    zone. "]

val build_info_as_sexp : Sexp.t
val reprint_build_info : (Time_float.t -> Sexp.t) -> string
val username : string option
val hostname : string option
val kernel : string option
val build_time : Time_float.t option
val x_library_inlining : bool
val dynlinkable_code : bool
val compiled_for_speed : bool
val application_specific_fields : Application_specific_fields.t option
val ocaml_version : string
val allowed_projections : string list option

val executable_path : string [@@ocaml.doc " Relative to OMakeroot dir "]

val build_system : string
val with_fdo : (string * Md5.t option) option

module For_tests : sig
  val parse_generated_hg_version : string -> string list
  val build_info_status : [ `Not_supported | `Unset | `Set ]
end

val build_system_supports_version_util : bool
[@@ocaml.doc
  " If [false], all the variables above are filled in with bogus values.\n\
  \    The value is [false] in tests at the moment. "]

module Expert : sig
  val get_version_util : contents_of_exe:string -> string option
  [@@ocaml.doc
    " Gets the version util if it exists.\n\n\
    \      Since 2022-11, this function is guaranteed to be bidirectionally compatible\n\
    \      if we ever change the version util format. We guarantee that:\n\n\
    \      - New versions of this function will always be able to parse the version\n\
    \        util out of all binaries built after 2022-11.\n\n\
    \      - Versions of this function which are less than one month old will always\n\
    \        be able to parse the version util out of new binaries. Older versions of\n\
    \        this function may not be able to parse the version util out of new \
     binaries.\n\n\
    \      If you care about performance, consider using \
     lib/fast_get_version_util_from_file.\n\
    \      It is around 10-20x faster than this function, which can take a small number of\n\
    \      seconds for several hundred megabyte binaries. "]

  val replace_version_util
    :  contents_of_exe:string
    -> Version.t list option
    -> string option
  [@@ocaml.doc
    " Inserts the given version util into the executable text given. Returns [None] if\n\
    \      this could not happen (e.g., the given executable has no version util \
     sections).\n\n\
    \      [None] means to remove the version util. The purpose is to make it possible to\n\
    \      compare executables up to version util. "]

  val parse_generated_hg_version : string -> string list
  [@@ocaml.doc
    " Turns raw hg version info into the standard string list format that [version_list]\n\
    \      returns. "]

  module Experimental : sig
    val get_build_info : contents_of_exe:string -> string option
    [@@ocaml.doc
      " Gets the build info if it exists.\n\n\
      \        This functionality is experimental and may be changed/removed with little \
       notice. "]

    val remove_build_info : contents_of_exe:string -> string option
    [@@ocaml.doc
      " Replaces the payload of all build info sections with the string \"NO_BUILD_INFO\".\n\
      \        Returns [None] if no build info section was found.\n\n\
      \        This functionality is experimental and may be changed/removed with little \
       notice. "]
  end

  module For_tests : sig
    val count_section_occurrences : contents_of_exe:string -> int
    [@@ocaml.doc " Includes version util and build info sections. "]
  end
end
[@@ocaml.doc
  " When you read the words \"version util\" below, try adding the word \"info\" to\n\
  \    them: \"version util info\" makes a little more sense. "]

module Private__For_version_util_async : sig
  val version_util_start_marker : string
  val parse_generated_hg_version : string -> string list
  val raw_text : Version.t list option -> string
end
