[@@@ocaml.text
  " Generators are sources of random values. Every randomized test needs a generator to\n\
  \    produce its inputs. "]

open! Base

type +'a t

[@@@ocaml.text
  " {2 Basic Generators}\n\n\
  \    These are good default generators for tests over types from OCaml and Base. They \
   are\n\
  \    designed to hit corner cases reasonably often, and also generate reasonably good\n\
  \    coverage of common cases and arbitrary values. "]

include With_basic_types.S with type 'a t := 'a t [@@ocaml.doc " @inline "]

val fn : 'a Observer0.t -> 'b t -> ('a -> 'b) t
[@@ocaml.doc
  " Generates random functions that use the given observer to perturb the pseudo-random\n\
  \    state that is then used to generate the output value. The resulting functions are\n\
  \    therefore deterministic, assuming the observer is deterministic. "]

val map_t_m
  :  ('key, 'cmp) Comparator.Module.t
  -> 'key t
  -> 'data t
  -> ('key, 'data, 'cmp) Map.t t

val set_t_m : ('elt, 'cmp) Comparator.Module.t -> 'elt t -> ('elt, 'cmp) Set.t t

val map_tree_using_comparator
  :  comparator:('key, 'cmp) Comparator.t
  -> 'key t
  -> 'data t
  -> ('key, 'data, 'cmp) Map.Using_comparator.Tree.t t

val set_tree_using_comparator
  :  comparator:('elt, 'cmp) Comparator.t
  -> 'elt t
  -> ('elt, 'cmp) Set.Using_comparator.Tree.t t

[@@@ocaml.text " {2 Combining and Modifying Generators} "]

val of_list : 'a list -> 'a t
[@@ocaml.doc " Produces any of the given values, weighted uniformly. "]

val union : 'a t list -> 'a t
[@@ocaml.doc
  " Chooses among the given generators, weighted uniformly; then chooses a value from that\n\
  \    generator. "]

include Applicative.S with type 'a t := 'a t
include Monad.S with type 'a t := 'a t

[@@@ocaml.text
  " {2 Size of Random Values}\n\n\
  \    Base_quickcheck threads a size parameter through generators to limit the size of\n\
  \    unbounded types. Users of Base_quickcheck often do not need to think about the size\n\
  \    parameter; the default generators handle it sensibly. Generators of atomic types\n\
  \    ignore it, generators of bounded-size containers like [both] and [either] thread it\n\
  \    through unchanged, and generators of unbounded-size containers like [list] and\n\
  \    [set_t_m] distribute the size they are given among their constituents.\n\n\
  \    The bindings below allow direct manipulation of the size parameter in cases where\n\
  \    users want a custom treatment of sizes. There is no prescribed meaning of the size\n\
  \    parameter for any given type other than that it must be non-negative. As a general\n\
  \    guideline, however, the time and space used to generate a value should be \
   proportional\n\
  \    to the size parameter at most.\n\n\
  \    The size parameter should be treated as an upper bound but not as a lower bound, so\n\
  \    for example a generator given a size parameter of 2 should have a chance to \
   generate\n\
  \    values of size 0 or 1 as well. If the size parameter is treated as a lower bound, \
   then\n\
  \    for example members of tuples will always be generated at the same size, and test\n\
  \    cases for members of different size will not be covered.\n"]

val size : int t [@@ocaml.doc " Returns the current size parameter. "]

val with_size : 'a t -> size:int -> 'a t
[@@ocaml.doc
  " Produces a generator that ignores the size parameter passed in by Base_quickcheck and\n\
  \    instead uses the given [~size] argument. Most often used with [size] to reduce the\n\
  \    size when dispatching to generators for subparts of a value.\n\n\
  \    For example, here is a use of [with_size] and [size] to create a generator for\n\
  \    optional lists. We are careful to generate [None] even at non-zero sizes; see the \
   note\n\
  \    above about not using [size] as a lower bound.\n\n\
  \    {[\n\
  \      let optional_list generator =\n\
  \        let open Let_syntax in\n\
  \        match%bind both size bool with\n\
  \        | (0, _) | (_, false) -> return None\n\
  \        | k, _ ->\n\
  \          let%map elements = with_size ~size:(k-1) (list generator) in\n\
  \          Some elements\n\
  \    ]}\n"]

val sizes : ?min_length:int -> ?max_length:int -> unit -> int list t
[@@ocaml.doc
  " Produces a list of sizes that distribute the current size among list elements. The\n\
  \    [min_length] and [max_length] parameters can be used to bound the length of the\n\
  \    result.\n\n\
  \    This is the distribution used by generators such as [list] to divide up size among\n\
  \    elements.\n\n\
  \    This function is designed so that elements of [list] are always generated at \
   strictly\n\
  \    smaller size than the list itself. The technical invariant is: if [size_list] is\n\
  \    generated by [with_size ~size:n (sizes ~min_length ())], then:\n\n\
  \    {[\n\
  \      (List.length size_list - min_length) + (List.sum (module Int) size_list)\n\
  \      <= n\n\
  \    ]} "]

[@@@ocaml.text " {2 Filtering Generators} "]

val filter : 'a t -> f:('a -> bool) -> 'a t
[@@ocaml.doc
  " Produces values for which [f] returns [true]. If [f] returns [false], retries with\n\
  \    [size] incremented by 1. This avoids [filter] getting stuck if all values at a \
   given\n\
  \    size fail [f]; see the note above about not using [size] as a lower bound. "]

val filter_map : 'a t -> f:('a -> 'b option) -> 'b t
[@@ocaml.doc
  " When [f] produces [Some x], produces [x]. If [f] returns [None], retries with [size]\n\
  \    incremented by 1, as with [filter]. "]

[@@@ocaml.text " {2 Generating Recursive Values} "]

val recursive_union : 'a t list -> f:('a t -> 'a t list) -> 'a t
[@@ocaml.doc
  " Ties the recursive knot to produce generators for recursive types that have multiple\n\
  \    clauses, separating base cases from recursive cases. At size 0, only base cases are\n\
  \    produced; at size [n > 0], the base cases are produced at size [n] along with the\n\
  \    recursive cases at size [n-1]. Raises if the list of base cases is empty or if the\n\
  \    list of recursive cases is empty.\n\n\
  \    For example, here is a use of [recursive_union] to create a generator for an\n\
  \    expression datatype.\n\n\
  \    {[\n\
  \      type exp =\n\
  \        | Int  of int\n\
  \        | Bool of bool\n\
  \        | If   of exp * exp * exp\n\
  \        | Add  of exp * exp\n\n\
  \      let exp_generator =\n\
  \        recursive_union\n\
  \          [\n\
  \            map int ~f:(fun i -> Int i);\n\
  \            map bool ~f:(fun b -> Bool b);\n\
  \          ]\n\
  \          ~f:(fun exp ->\n\
  \            let open Let_syntax in\n\
  \            [\n\
  \              (let%map a = exp and b = exp and c = exp in If (a, b, c));\n\
  \              (let%map a = exp and b = exp in Add (a, b));\n\
  \            ])\n\
  \    ]} "]

val fixed_point : ('a t -> 'a t) -> 'a t
[@@ocaml.doc
  " Like [recursive_union], without separate clauses or automatic size management. Useful\n\
  \    for generating recursive types that don't fit the clause structure of\n\
  \    [recursive_union].\n\n\
  \    For example, here is a use of [fixed_point] to create a generator for N-ary \
   trees. No\n\
  \    manual size management is needed, as [Generator.list] guarantees to generate list\n\
  \    elements at strictly smaller sizes than the list itself.\n\n\
  \    {[\n\
  \      type tree = Node of tree list\n\
  \      let tree_generator =\n\
  \        fixed_point (fun tree ->\n\
  \          map (list tree) ~f:(fun trees -> Node trees))\n\
  \    ]}\n"]

val of_lazy : 'a t Lazy.t -> 'a t
[@@ocaml.doc
  " Creates a [t] that forces the lazy argument as necessary. Can be used to tie\n\
  \    (mutually) recursive knots. "]

[@@@ocaml.text " {2 Custom Random Distributions} "]

val of_weighted_list : (float * 'a) list -> 'a t
[@@ocaml.doc
  " Produces one of the given values, chosen with the corresponding weight. Weights must\n\
  \    be non-negative and must have a strictly positive sum. "]

val weighted_union : (float * 'a t) list -> 'a t
[@@ocaml.doc
  " Produces one of the given generators, chosen with the corresponding weight, then\n\
  \    chooses a value from that generator. Weights must be non-negative and must have a\n\
  \    strictly positive sum. "]

val weighted_recursive_union
  :  (float * 'a t) list
  -> f:('a t -> (float * 'a t) list)
  -> 'a t
[@@ocaml.doc
  " Like [recursive_union], with explicit weights for each clause. Weights must be\n\
  \    non-negative and the recursive case weights must have a strictly positive sum. "]

[@@@ocaml.text " {3 Integer Distributions} "]

val small_positive_or_zero_int : int t
[@@ocaml.doc
  " Produces an integer between 0 and an unspecified upper bound which is proportional to\n\
  \    [size]. This is a good generator to use for sizes of values like strings which \
   have a\n\
  \    variable number of fixed-size elements. "]

val small_strictly_positive_int : int t
[@@ocaml.doc " Like [small_positive_or_zero_int] but with a minimum of [1]. "]

[@@@ocaml.text
  " {4 Uniform Unbounded Distributions}\n\n\
  \    These generators produce any value of the relevant integer type with uniform \
   weight.\n\
  \    The default generators for these types differ in that they give higher weight to\n\
  \    corner cases, e.g. [min_value] and [max_value].\n"]

val int_uniform : int t
val int32_uniform : int32 t
val int63_uniform : Int63.t t
val int64_uniform : int64 t
val nativeint_uniform : nativeint t

[@@@ocaml.text
  " {4 Bounded Distributions}\n\n\
  \    These generators produce any value between the given inclusive bounds, which must \
   be\n\
  \    given in nondecreasing order. Higher weight is given to corner cases, e.g. the \
   bounds\n\
  \    themselves.\n"]

val int_inclusive : int -> int -> int t
val int32_inclusive : int32 -> int32 -> int32 t
val int63_inclusive : Int63.t -> Int63.t -> Int63.t t
val int64_inclusive : int64 -> int64 -> int64 t
val nativeint_inclusive : nativeint -> nativeint -> nativeint t

[@@@ocaml.text
  " {4 Uniform Bounded Distributions}\n\n\
  \    These generators produce any value between the given inclusive bounds, which must \
   be\n\
  \    given in nondecreasing order. All values are given equal weight.\n"]

val int_uniform_inclusive : int -> int -> int t
val int32_uniform_inclusive : int32 -> int32 -> int32 t
val int63_uniform_inclusive : Int63.t -> Int63.t -> Int63.t t
val int64_uniform_inclusive : int64 -> int64 -> int64 t
val nativeint_uniform_inclusive : nativeint -> nativeint -> nativeint t

[@@@ocaml.text
  " {4 Uniform in Log Space Distributions}\n\n\
  \    These generators produce any value between the given inclusive, non-negative \
   bounds,\n\
  \    choosing bit-length in that range uniformly and then uniformly among values with \
   that\n\
  \    bit-length between the bounds. The bounds must be given in nondecreasing order.\n"]

val int_log_uniform_inclusive : int -> int -> int t
val int32_log_uniform_inclusive : int32 -> int32 -> int32 t
val int63_log_uniform_inclusive : Int63.t -> Int63.t -> Int63.t t
val int64_log_uniform_inclusive : int64 -> int64 -> int64 t
val nativeint_log_uniform_inclusive : nativeint -> nativeint -> nativeint t

[@@@ocaml.text
  " {4 Log Space Distributions}\n\n\
  \    Like the [*_log_uniform_inclusive] bindings above, but giving additional weight to\n\
  \    corner cases, e.g. the given bounds.\n"]

val int_log_inclusive : int -> int -> int t
val int32_log_inclusive : int32 -> int32 -> int32 t
val int63_log_inclusive : Int63.t -> Int63.t -> Int63.t t
val int64_log_inclusive : int64 -> int64 -> int64 t
val nativeint_log_inclusive : nativeint -> nativeint -> nativeint t

[@@@ocaml.text
  " {4 Geometric Distributions}\n\n\
  \    These generators produce a geometric distribution with a given minimum and \
   probabilty\n\
  \    [p]. In other words, with probability [p], the minimum is produced. Otherwise, a \
   value\n\
  \    is effectively produced from a geometric distribution with the same [p] and a \
   minimum\n\
  \    one higher, although the implementation can be more efficent than this. If the \
   result\n\
  \    overflows, the function returns [max_value] for the integer type.\n\n\
  \    Raises if [p <. 0. || 1. <. p.]. "]

val int_geometric : int -> p:float -> int t
val int32_geometric : int32 -> p:float -> int32 t
val int63_geometric : Int63.t -> p:float -> Int63.t t
val int64_geometric : int64 -> p:float -> int64 t
val nativeint_geometric : nativeint -> p:float -> nativeint t

[@@@ocaml.text " {3 Floating Point Distributions} "]

val float_inclusive : float -> float -> float t
[@@ocaml.doc
  " Generates values between the given bounds, inclusive, which must be finite and in\n\
  \    nondecreasing order. Weighted toward boundary values. "]

val float_uniform_exclusive : float -> float -> float t
[@@ocaml.doc
  " Generates values between the given bounds, exclusive, which must be finite and in\n\
  \    increasing order, with at least one float value between them. Weighted \
   approximately\n\
  \    uniformly across the resulting range, rounding error notwithstanding. "]

val float_without_nan : float t
val float_finite : float t
val float_strictly_positive : float t
val float_strictly_negative : float t
val float_positive_or_zero : float t
val float_negative_or_zero : float t
val float_of_class : Float.Class.t -> float t

[@@@ocaml.text " {3 Character Distributions} "]

val char_lowercase : char t
val char_uppercase : char t
val char_digit : char t
val char_alpha : char t
val char_alphanum : char t
val char_whitespace : char t
val char_print : char t
val char_uniform_inclusive : char -> char -> char t

[@@@ocaml.text " {3 String Distributions} "]

val string_non_empty : string t
val string_with_length : length:int -> string t
val string_of : char t -> string t
val string_non_empty_of : char t -> string t
val string_with_length_of : char t -> length:int -> string t

val string_like : string -> string t
[@@ocaml.doc " Produces strings similar to the input, with some number of edits. "]

[@@@ocaml.text " {3 Sexp Distributions} "]

val sexp_of : string t -> Sexp.t t
[@@ocaml.doc
  " Produces s-expressions whose atoms are chosen from the given string distribution. "]

[@@@ocaml.text " {3 List Distributions} "]

val list_non_empty : 'a t -> 'a list t
val list_with_length : 'a t -> length:int -> 'a list t

val list_filtered : 'a list -> 'a list t
[@@ocaml.doc
  " Randomly drops elements from a list. The length of each result is chosen uniformly\n\
  \    between 0 and the length of the input, inclusive. "]

val list_permutations : 'a list -> 'a list t
[@@ocaml.doc " Produces permutations of the given list, weighted uniformly. "]

include sig
  open Bigarray

  val bigarray1
    :  'a t
    -> ('a, 'b) kind
    -> 'c layout
    -> length:int option
    -> ('a, 'b, 'c) Array1.t t

  val bigstring_with_length : length:int -> (char, int8_unsigned_elt, c_layout) Array1.t t

  val float32_vec_with_length
    :  length:int
    -> (float, float32_elt, fortran_layout) Array1.t t

  val float64_vec_with_length
    :  length:int
    -> (float, float64_elt, fortran_layout) Array1.t t
end
[@@ocaml.doc " {3 Bigarray Distributions} "] [@@ocaml.doc " @inline "]

[@@@ocaml.text
  " {2 Low-Level Interface}\n\n\
  \    These functions provide direct access to the pseudo-random state threaded through\n\
  \    Base_quickcheck generators. Most users should not need these functions.\n"]

val perturb : 'a t -> int -> 'a t
[@@ocaml.doc
  " Passes in additional \"salt\" used to perturb the pseudo-random state used to generate\n\
  \    random values. Generators' output is intended to be deterministic for any initial\n\
  \    pseudorandom state, so [perturb] can be used to generate a new generator with the \
   same\n\
  \    distribution that nonetheless produces different values from the original for any\n\
  \    given pseudo-random state. "]

val create : (size:int -> random:Splittable_random.t -> 'a) -> 'a t
[@@ocaml.doc
  " Creates a generator that calls the given function with the current size parameter and\n\
  \    pseudorandom state. "]

val generate : 'a t -> size:int -> random:Splittable_random.t -> 'a
[@@ocaml.doc
  " Generates a random value using the given size and pseudorandom state. Useful when\n\
  \    using [create] and dispatching to other existing generators. "]

module Debug : sig
  [@@@ocaml.text " {3 Helpers for debugging generators} "]

  val coverage
    :  (module Comparator.S with type t = 'k and type comparator_witness = 'cmp)
    -> 'k Sequence.t
    -> ('k, int, 'cmp) Map.t
  [@@ocaml.doc
    " [coverage (module Key) sample] counts how many times each key appears in [sample].\n\n\
    \      See [Test.with_sample] for a convenient way to generate [sample]. "]

  val monitor : 'a t -> f:('a -> unit) -> 'a t
  [@@ocaml.doc
    " [monitor t ~f] returns a generator which gives the same values as [t] and also calls\n\
    \      [f] for each value. This can help diagnose behavior of generators \"hidden\" \
     behind\n\
    \      [map], [filter], etc. One might count the number of values a generator \
     produces, or\n\
    \      record the set of values that do not satisfy some filter. "]
end
