[@@@ocaml.text
  " Disallows the empty string and whitespace around the edges in [of_string] and\n\
  \    [t_of_sexp], but doesn't check when reading from bin_io. "]

let () = Ppx_bench_lib.Benchmark_accumulator.Current_libname.set "ppx_inline_test_lib_1"

let () =
  Ppx_expect_runtime.Current_file.set
    ~filename_rel_to_project_root:"string_id_intf.ml.before-ppx"
;;

let () =
  Ppx_inline_test_lib.set_lib_and_partition
    "ppx_inline_test_lib_1"
    "string_id_intf.ml.before-ppx"
;;

open! Import
open Std_internal

module type S = sig
  type t = private string [@@deriving equal, globalize, hash, sexp_grammar]

  include sig
    [@@@ocaml.warning "-32"]

    include Ppx_compare_lib.Equal.S with type t := t

    val globalize : t -> t

    include Ppx_hash_lib.Hashable.S with type t := t

    val t_sexp_grammar : t Sexplib0.Sexp_grammar.t
  end
  [@@ocaml.doc "@inline"] [@@merlin.hide]

  include Identifiable with type t := t
  include Quickcheckable.S with type t := t
  include Diffable.S_atomic with type t := t

  val arg_type : t Command.Arg_type.t

  module Stable : sig
    module V1 : sig
      type nonrec t = t [@@deriving equal, hash, sexp_grammar, stable_witness]

      include sig
        [@@@ocaml.warning "-32"]

        include Ppx_compare_lib.Equal.S with type t := t
        include Ppx_hash_lib.Hashable.S with type t := t

        val t_sexp_grammar : t Sexplib0.Sexp_grammar.t
        val stable_witness : t Ppx_stable_witness_runtime.Stable_witness.t
      end
      [@@ocaml.doc "@inline"] [@@merlin.hide]

      include Stringable.S with type t := t

      include
        Stable_comparable.With_stable_witness.V1
        with type t := t
        with type comparator_witness = comparator_witness

      include Hashable.Stable.V1.With_stable_witness.S with type key := t
      include Diffable.S_atomic with type t := t
    end
  end
end

module type S_with_extras = sig
  type t = private string [@@deriving typerep]

  include sig
    [@@@ocaml.warning "-32"]

    include Typerep_lib.Typerepable.S with type t := t
  end
  [@@ocaml.doc "@inline"] [@@merlin.hide]

  include S with type t := t
end
[@@ocaml.doc
  " Some extra features we provide in [Make] and other functors here,\n\
  \    but don't want to require of any string ID like type.\n"]

module type String_id = sig
  module type S = S
  module type S_with_extras = S_with_extras

  include S

  module Make : functor
      (M : sig
         val module_name : string
       end)
      -> functor ()
      -> S_with_extras
  [@@ocaml.doc
    " [Make] customizes the error messages generated by [of_string]/[of_sexp] to include\n\
    \      [module_name].  It also registers a pretty printer.\n\n\
    \      Note that the results of applying Make all have the same Bin_prot.Shape.  \
     This is\n\
    \      usually not what you want, and it's recommended to use \
     Make_with_distinct_shape to\n\
    \      provide different shapes for different identifier types.\n\n\
    \      The resulting [quickcheck_generator] generates non-empty strings containing \
     only\n\
    \      printable characters, and no whitespace at the edges. "]

  module Make_with_distinct_bin_shape : functor
      (M : sig
         val module_name : string
         val caller_identity : Bin_prot.Shape.Uuid.t
       end)
      -> functor ()
      -> S_with_extras
  [@@ocaml.doc
    " Like [Make], but lets you specify a [caller_identity] to ensure that the bin-shape\n\
    \      is distinct, which helps catch serialization bugs where identifiers with \
     different\n\
    \      meanings get confused with each other. "]

  module Make_with_validate : functor
      (M : sig
         val module_name : string
         val validate : string -> unit Or_error.t

         val include_default_validation : bool
         [@@ocaml.doc
           " By default, String_id performs some validation of its own in addition to \
            calling\n\
           \             [validate], namely:\n\n\
           \             - The string cannot be empty;\n\
           \             - The string may not have whitespace at the beginning or the \
            end.\n\n\
           \             You can turn this validation off using this flag. "]
       end)
      -> functor ()
      -> S_with_extras
  [@@ocaml.doc
    " [Make_with_validate] is like [Make], but modifies [of_string]/[of_sexp]/[bin_read_t]\n\
    \      to raise if [validate] returns an error.  Before using this functor\n\
    \      one should be mindful of the performance implications (the [validate] function\n\
    \      will run every time an instance is created) as well as potential versioning \
     issues\n\
    \      (when [validate] changes old binaries still run the old version of the \
     function).\n\n\
    \      The resulting [quickcheck_generator] uses a naive [Generator.filter] to satisfy\n\
    \      [validate]. For complex validation predictes, the generator may spin \
     indefinitely\n\
    \      trying to generate a satisfying string. In these cases, the client should \
     shadow\n\
    \      [quickcheck_generator] with a generator that constructs valid strings more \
     directly.\n\
    \  "]

  module Make_without_pretty_printer : functor
      (M : sig
         val module_name : string
       end)
      -> functor ()
      -> S_with_extras
  [@@ocaml.doc
    " This does what [Make] does without registering a pretty printer.  Use this when the\n\
    \      module that is made is not exposed in mli.  Registering a pretty printer \
     without\n\
    \      exposing it causes an error in utop. "]

  module Make_with_validate_without_pretty_printer : functor
      (M : sig
         val module_name : string
         val validate : string -> unit Or_error.t
         val include_default_validation : bool
       end)
      -> functor ()
      -> S_with_extras
  [@@ocaml.doc " See [Make_with_validate] and [Make_without_pretty_printer] "]

  module String_without_validation_without_pretty_printer : S with type t = string
end

let () = Ppx_inline_test_lib.unset_lib "ppx_inline_test_lib_1"
let () = Ppx_expect_runtime.Current_file.unset ()
let () = Ppx_bench_lib.Benchmark_accumulator.Current_libname.unset ()
